"""
DjangoProject settings for DjangoProject project.

Generated by 'django-admin startproject' using Django 4.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import json
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def get_secret(secret_name, default_value=None, cast_type=None):
    """
    从环境变量或文件中获取secret，并支持类型转换
    
    Args:
        secret_name (str): 环境变量名称
        default_value: 默认值
        cast_type (type): 值的类型，如 bool, int, float等
    
    Returns:
        处理后的配置值
    """
    import logging
    logger = logging.getLogger(__name__)
    
    # 首先尝试从环境变量获取
    secret = os.environ.get(secret_name)
    source = None
    
    if secret is not None:
        source = "environment variable"
    else:
        # 如果环境变量中没有，尝试从文件中读取（适用于Docker secrets）
        secret_file_var = f'{secret_name}_FILE'
        secret_file = os.environ.get(secret_file_var)
        if secret_file:
            try:
                # 安全验证：限制文件路径到安全目录
                safe_base = Path('/run/secrets')  # Docker secrets 标准路径
                secret_path = Path(secret_file).resolve()
                
                # 检查路径是否在安全目录内
                if not str(secret_path).startswith(str(safe_base)):
                    logger.warning(f"Unsafe path: {secret_file}")
                    return _cast_value(default_value, cast_type)
                
                try:
                    with open(secret_path, 'r', encoding='utf-8') as f:
                        secret = f.read().strip()
                        source = "secret file"
                except IOError as e:
                    logger.warning(f"Could not read secret file {secret_file}: {e}")
            except Exception as e:
                logger.warning(f"Error processing secret file for {secret_name}: {e}")
    
    # 如果都没有找到，则使用默认值
    if secret is None:
        secret = default_value
        # 不记录默认值的使用，避免生产环境信息泄露
    else:
        # 对特殊字符串进行类型转换
        if isinstance(secret, str):
            if secret.lower() in ('true', 'false'):
                secret = secret.lower() == 'true'
            elif secret.lower() in ('null', 'none'):
                secret = None
            elif secret.isdigit():
                secret = int(secret)
            elif _is_float(secret):
                secret = float(secret)
    
    # 执行最终的类型转换
    return _cast_value(secret, cast_type)

def _cast_value(value, cast_type):
    """辅助函数：执行值的类型转换"""
    if cast_type is None or value is None:
        return value
    # 空字符串转 int 时视为“未设置”，返回 None（如 DB_PORT 用默认端口）
    if cast_type == int and isinstance(value, str) and value.strip() == '':
        return None
    try:
        if cast_type == bool and isinstance(value, str):
            return value.lower() == 'true'
        return cast_type(value)
    except (ValueError, TypeError):
        import logging
        logging.getLogger(__name__).warning(f"Could not cast {value} to {cast_type}")
        return value

def _is_float(value):
    """检查字符串是否为浮点数"""
    try:
        float(value)
        return True
    except ValueError:
        return False


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret('SECRET_KEY', 'django-insecure-5+w=@93(d0n2n)l$_!@314z%!4+7^_7w5%0+0w@&$k!35%3@u6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_secret('DEBUG', False, bool)

# 线上是否暴露 API 文档（/swagger/、/redoc/）。默认与 DEBUG 一致，生产环境建议关闭以免暴露接口结构
ENABLE_API_DOCS = get_secret('ENABLE_API_DOCS', DEBUG, bool)

# 获取允许的主机列表，确保开发环境的主机总是被包含
allowed_hosts_str = get_secret('DJANGO_ALLOWED_HOSTS', '*')
if allowed_hosts_str == '*':
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = allowed_hosts_str.split(' ')
    # 确保开发环境的主机总是被包含
    dev_hosts = ['127.0.0.1', 'localhost']
    for host in dev_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

# 内网访问 admin 时，需把访问用的「协议+域名/IP」加到这里，如 http://192.168.1.10、https://api.xxx.com
CSRF_TRUSTED_ORIGINS = [
    x.strip() for x in get_secret(
        'DJANGO_CSRF_TRUSTED_ORIGINS',
        'http://localhost,http://127.0.0.1,http://0.0.0.0,http://127.0.0.1:8001,http://localhost:8001'
    ).split(',')
    if x.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'drf_yasg',
    'authentication',
    'common',
    'testcases',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'common.cloudflare_middleware.CloudflareOnlyMiddleware',  # 重新启用
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'common.disable_csrf.DisableCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DjangoProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DjangoProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# 解析数据库选项
db_options_str = get_secret('DB_OPTIONS', '{}')
try:
    db_options = json.loads(db_options_str)
except json.JSONDecodeError as e:
    import logging
    logging.getLogger(__name__).warning(f"Invalid DB_OPTIONS JSON: {e}. Using empty options.")
    db_options = {}

DATABASES = {
    'default': {
        'ENGINE': get_secret('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': get_secret('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': get_secret('DB_USER', ''),
        'PASSWORD': get_secret('DB_PASSWORD', ''),
        'HOST': get_secret('DB_HOST', ''),
        'PORT': get_secret('DB_PORT', '', int),  # 端口应该是整数
        'OPTIONS': db_options,
    }
}

# 连接池设置
DATABASES['default']['CONN_MAX_AGE'] = 60
# DATABASES['default']['OPTIONS']['MAX_CONNS'] = 20  # 移除了无效的MAX_CONNS设置


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Manifest 存储需要先执行 collectstatic 且要求所有静态文件都在 manifest 中；
# drf-yasg 的 Swagger UI 在未 collect 时会报 Missing staticfiles manifest entry 导致 /swagger/ 500。
# 使用 CompressedStaticFilesStorage 可在未生成 manifest 时正常生成静态 URL，避免该 500。
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# DRF settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        # 移除SessionAuthentication以避免CSRF检查
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour'
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

RATELIMIT_VIEW = 'authentication.views.ratelimited'

# CSRF_TRUSTED_ORIGINS 已在上方统一配置

# 添加以下内容：
CSRF_COOKIE_HTTPONLY = False  # 允许JavaScript访问CSRF cookie

# JWT settings
from datetime import timedelta
import secrets

# 生成强随机JWT签名密钥（生产环境应使用环境变量）
JWT_SIGNING_KEY = get_secret('JWT_SIGNING_KEY', secrets.token_urlsafe(64))

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),  # 增加到15分钟
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # 减少到7天
    "ROTATE_REFRESH_TOKENS": True,                  # 启用令牌轮转
    "BLACKLIST_AFTER_ROTATION": True,               # 轮转后加入黑名单
    "UPDATE_LAST_LOGIN": True,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": JWT_SIGNING_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=15),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=7),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# CORS settings - 动态配置支持
CORS_ALLOW_ALL_ORIGINS = get_secret('CORS_ALLOW_ALL_ORIGINS', False, bool)

# 默认允许的域名
default_origins = [
    'https://www.baiyila1016.top',
    'https://baiyila1016.top',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# 从环境变量获取额外的域名
env_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []
env_origins = [origin.strip() for origin in env_origins if origin.strip()]

# 合并默认域名和环境变量域名
CORS_ALLOWED_ORIGINS = default_origins + env_origins

# 清理空字符串
CORS_ALLOWED_ORIGINS = [origin for origin in CORS_ALLOWED_ORIGINS if origin]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'sec-ch-ua',
    'sec-ch-ua-mobile',
    'sec-ch-ua-platform',
]
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# 内存优化设置
SESSION_ENGINE = 'django.contrib.sessions.backends.cache'

# 安全设置
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Cloudflare IP 范围（2024年最新版本）
CLOUDFLARE_IPS = [
    # IPv4 ranges
    '173.245.48.0/20',
    '103.21.244.0/22',
    '103.22.200.0/22',
    '103.31.4.0/22',
    '141.101.64.0/18',
    '108.162.192.0/18',
    '190.93.240.0/20',
    '188.114.96.0/20',
    '197.234.240.0/22',
    '198.41.128.0/17',
    '162.158.0.0/15',
    '104.16.0.0/13',
    '104.24.0.0/14',
    '172.64.0.0/13',
    '131.0.72.0/22',
    # 新增的IPv4范围
    '172.67.0.0/16',
    '104.21.0.0/16',
    # IPv6 ranges
    '2400:cb00::/32',
    '2606:4700::/32',
    '2803:f800::/32',
    '2405:b500::/32',
    '2405:8100::/32',
    '2a06:98c0::/29',
    '2c0f:f248::/32',
]

# 生产环境配置（通过 Cloudflare）
if not DEBUG:
    # 不强制 SSL 重定向，因为 Cloudflare 处理 HTTPS
    SECURE_SSL_REDIRECT = False
    # 信任 Cloudflare 的代理头
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Cookie 安全：内网用 HTTP 访问 admin 时设为 False，否则 CSRF cookie 不会发送导致 403
    SESSION_COOKIE_SECURE = get_secret('SESSION_COOKIE_SECURE', True, bool)
    CSRF_COOKIE_SECURE = get_secret('CSRF_COOKIE_SECURE', True, bool)
    # 获取真实 IP
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'authentication_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'authentication.log'),
            'maxBytes': 1024*1024*5,  # 5MB
            'backupCount': 5,
            'formatter': 'verbose',
            'delay': True,  # Delay file opening until first log
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'authentication': {
            'handlers': ['authentication_file', 'console'],
            'level': 'INFO',
            'propagate': True,  # 允许传播到django.log
        },
        'cloudflare_middleware': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}