# Generated by Django 6.0.4 on 2026-04-22 13:07

import common.snowflake
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.BigIntegerField(default=common.snowflake.generate_snowflake_id, editable=False, unique=True, verbose_name='公共ID')),
                ('product', models.CharField(blank=True, max_length=100, verbose_name='产品')),
                ('module', models.CharField(blank=True, max_length=100, verbose_name='功能模块')),
                ('sub_module', models.CharField(blank=True, max_length=100, verbose_name='子模块')),
                ('test_point', models.CharField(blank=True, max_length=200, verbose_name='测试点')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('precondition', models.TextField(blank=True, verbose_name='前置条件')),
                ('steps', models.TextField(blank=True, help_text='每行一个步骤', verbose_name='测试步骤')),
                ('expected_result', models.TextField(blank=True, verbose_name='预期结果')),
                ('actual_result', models.TextField(blank=True, verbose_name='实际结果')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '紧急')], default='medium', max_length=20, verbose_name='优先级')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('deprecated', '已废弃')], default='draft', max_length=20, verbose_name='状态')),
                ('is_smoke', models.BooleanField(default=False, verbose_name='是否为冒烟用例')),
                ('case_type', models.CharField(blank=True, max_length=50, verbose_name='用例类型')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_test_cases', to=settings.AUTH_USER_MODEL, verbose_name='修改人')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'testcases',
                'ordering': ['-updated_at'],
            },
        ),
    ]
