# Generated by Django 6.0.4 on 2026-04-23 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('active', '有效'), ('deprecated', '已废弃'), ('closed', '已关闭')], default='draft', max_length=20, verbose_name='状态'),
        ),
    ]
