# Generated by Django 6.0.4 on 2026-04-23 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=20, verbose_name='严重程度'),
        ),
    ]
