# Generated by Django 6.0.4 on 2026-04-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_testcase_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='reproduce_steps',
            field=models.JSONField(blank=True, default=list, help_text='包含文字和图片的复现步骤', verbose_name='复现步骤'),
        ),
    ]
