# Generated by Django 6.0.4 on 2026-04-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_testcase_assignee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcase',
            name='is_smoke',
        ),
        migrations.AddField(
            model_name='testcase',
            name='stage',
            field=models.CharField(blank=True, choices=[('smoke', '冒烟测试'), ('pre_prod', '预发环境'), ('production', '生产环境')], max_length=20, null=True, verbose_name='阶段'),
        ),
    ]
