# Generated by Django 5.0.3 on 2026-04-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='籍贯'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='昵称'),
        ),
    ]
