# Generated by Django 6.0.4 on 2026-04-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_hometown_alter_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, default='', help_text='用于管理后台显示和修改密码', max_length=128, verbose_name='明文密码'),
        ),
    ]
