# Generated by Django 6.0.4 on 2026-04-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_hint',
            field=models.CharField(blank=True, default='', help_text='用于找回密码的提示信息', max_length=200, verbose_name='密码提示'),
        ),
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.CharField(blank=True, default='', help_text='格式：xx省xx市', max_length=100, verbose_name='籍贯'),
        ),
    ]
