# Generated by Django 6.0.4 on 2026-04-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_password_hint_alter_user_hometown'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='period',
            field=models.CharField(blank=True, default='', help_text='格式：xxxx-xx-xx期学员，例如：2024-01-01期学员', max_length=50, verbose_name='期数'),
        ),
    ]
