# Generated by Django 6.0.4 on 2026-04-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_status',
            field=models.CharField(choices=[('studying', '在读'), ('graduated', '毕业')], default='studying', help_text='学员的学习状态：在读或毕业', max_length=20, verbose_name='学习状态'),
        ),
    ]
