# Generated by Django 6.0.4 on 2026-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_study_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', help_text='性别：男或女', max_length=10, verbose_name='性别'),
        ),
    ]
