# Generated by Django 6.0.4 on 2026-04-29 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('image', models.ImageField(upload_to='banners/%Y/%m/', verbose_name='图片')),
                ('link', models.URLField(blank=True, help_text='点击轮播图跳转的链接', verbose_name='链接地址')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='排序')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '禁用')], default='active', max_length=10, verbose_name='状态')),
                ('start_time', models.DateTimeField(blank=True, help_text='留空则立即生效', null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, help_text='留空则永久有效', null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
                'db_table': 'banner',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
