# Generated by Django 5.0.3 on 2026-04-22 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField(choices=[(1, '阶段1'), (2, '阶段2'), (3, '阶段3')], verbose_name='阶段')),
                ('subject', models.CharField(max_length=50, verbose_name='科目')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], max_length=20, verbose_name='难度')),
                ('content', models.TextField(verbose_name='题目内容')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/images/', verbose_name='题目图片')),
                ('voice', models.FileField(blank=True, null=True, upload_to='questions/audio/', verbose_name='题目语音')),
                ('answer', models.TextField(verbose_name='答案')),
                ('explanation', models.TextField(blank=True, verbose_name='解析')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '题目',
                'verbose_name_plural': '题目',
                'db_table': 'questions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作业标题')),
                ('stage', models.IntegerField(choices=[(1, '阶段1'), (2, '阶段2'), (3, '阶段3')], verbose_name='阶段')),
                ('question_count', models.IntegerField(default=10, verbose_name='题目数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('questions', models.ManyToManyField(to='questions.question', verbose_name='题目列表')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='questions.questioncategory')),
            ],
            options={
                'verbose_name': '题目分类',
                'verbose_name_plural': '题目分类',
                'db_table': 'question_categories',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.questioncategory', verbose_name='分类'),
        ),
        migrations.CreateModel(
            name='UserAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='得分')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.assignment', verbose_name='作业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户作业',
                'verbose_name_plural': '用户作业',
                'db_table': 'user_assignments',
                'unique_together': {('user', 'assignment')},
            },
        ),
        migrations.CreateModel(
            name='WrongQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.TextField(blank=True, verbose_name='用户答案')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否答对')),
                ('attempt_count', models.IntegerField(default=1, verbose_name='尝试次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='题目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '错题',
                'verbose_name_plural': '错题本',
                'db_table': 'wrong_questions',
                'unique_together': {('user', 'question')},
            },
        ),
    ]
