# Generated by Django 6.0.4 on 2026-04-28 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userassignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='wrongquestion',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userassignment',
            constraint=models.UniqueConstraint(fields=('user', 'assignment'), name='unique_user_assignment'),
        ),
        migrations.AddConstraint(
            model_name='wrongquestion',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question'),
        ),
    ]
