# Generated by Django 5.0.3 on 2026-04-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('company', models.CharField(max_length=200, verbose_name='公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('salary', models.IntegerField(verbose_name='薪资')),
                ('student_name', models.CharField(max_length=50, verbose_name='学员姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '就业统计',
                'verbose_name_plural': '就业统计',
                'db_table': 'employment_stats',
                'ordering': ['-salary'],
            },
        ),
        migrations.CreateModel(
            name='ExcellentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('avatar', models.ImageField(upload_to='students/', verbose_name='头像')),
                ('period', models.CharField(max_length=50, verbose_name='期数')),
                ('company', models.CharField(max_length=200, verbose_name='就业公司')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('salary', models.IntegerField(verbose_name='薪资')),
                ('testimonial', models.TextField(blank=True, verbose_name='感言')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '优秀学员',
                'verbose_name_plural': '优秀学员',
                'db_table': 'excellent_students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='答案')),
                ('category', models.CharField(max_length=50, verbose_name='分类')),
                ('frequency', models.IntegerField(default=0, verbose_name='出现频率')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '面试题',
                'verbose_name_plural': '面试题',
                'db_table': 'interview_questions',
                'ordering': ['-frequency'],
            },
        ),
        migrations.CreateModel(
            name='StudentStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=50, verbose_name='期数')),
                ('province', models.CharField(max_length=50, verbose_name='省份')),
                ('city', models.CharField(max_length=50, verbose_name='城市')),
                ('count', models.IntegerField(default=0, verbose_name='人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学员统计',
                'verbose_name_plural': '学员统计',
                'db_table': 'student_stats',
            },
        ),
    ]
