# Generated by Django 5.0.3 on 2026-04-28 07:53

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
        ('users', '0007_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatisticsProxy',
            fields=[
            ],
            options={
                'verbose_name': '学员统计',
                'verbose_name_plural': '学员统计',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='employmentstats',
            name='period',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='期数'),
        ),
    ]
