# Generated by Django 6.0.4 on 2026-04-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_studentstatisticsproxy_employmentstats_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentstats',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别'),
        ),
    ]
