# Generated by Django 6.0.4 on 2026-04-28 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_employmentstats_gender'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentstats',
            name='student',
            field=models.ForeignKey(blank=True, help_text='关联的学员用户，期数和性别将自动从用户信息中获取', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_records', to=settings.AUTH_USER_MODEL, verbose_name='学员'),
        ),
        migrations.AlterField(
            model_name='employmentstats',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', help_text='学员性别（优先从关联用户获取）', max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='employmentstats',
            name='period',
            field=models.CharField(blank=True, default='', help_text='学员期数（优先从关联用户获取）', max_length=50, verbose_name='期数'),
        ),
        migrations.AlterField(
            model_name='employmentstats',
            name='student_name',
            field=models.CharField(help_text='学员姓名（如果未关联用户则手动填写）', max_length=50, verbose_name='学员姓名'),
        ),
    ]
