# Generated by Django 6.0.4 on 2026-04-28 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_employmentstats_student_alter_employmentstats_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dormitory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='学员姓名（自动从关联用户获取）', max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女')], default='', max_length=10, verbose_name='性别')),
                ('period', models.CharField(blank=True, default='', max_length=50, verbose_name='期数')),
                ('hometown', models.CharField(blank=True, default='', max_length=100, verbose_name='籍贯')),
                ('dormitory', models.CharField(help_text='宿舍号，例如：A栋101', max_length=50, verbose_name='宿舍')),
                ('phone', models.CharField(blank=True, default='', max_length=11, verbose_name='手机号')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.OneToOneField(help_text='关联的学员用户，姓名、性别、期数、籍贯、手机号将自动从用户信息中获取', on_delete=django.db.models.deletion.CASCADE, related_name='dormitory_info', to=settings.AUTH_USER_MODEL, verbose_name='学员')),
            ],
            options={
                'verbose_name': '宿舍管理',
                'verbose_name_plural': '宿舍管理',
                'db_table': 'dormitories',
                'ordering': ['dormitory', 'student_name'],
            },
        ),
    ]
