# Generated by Django 6.0.4 on 2026-04-28 08:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityparticipant',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='表单数据'),
        ),
        migrations.AlterField(
            model_name='activityparticipant',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='提交数据'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipant',
            constraint=models.UniqueConstraint(fields=('activity', 'user'), name='unique_activity_user'),
        ),
    ]
